# CONFIG_.yaml



METADATA:
  SPANISH:
    'Author': 'Ibon Mart铆nez-Arranz (@imarranz)'
    'Title': 'Rompiendo C贸digos, Creando Futuro'
    'Subject': 'El Pionero de la Computaci贸n: C贸mo Alan Turing Descifr贸 Enigma y Transform贸 el Mundo'
    'Keywords': 'Alan Turing, Inteligencia Artificial, Enigma'
  ENGLISH:
    'Author': 'Ibon Mart铆nez-Arranz (@imarranz)'
    'Title': 'Breaking Codes, Creating the Future'
    'Subject': 'The Pioneer of Computing: How Alan Turing Cracked Enigma and Transformed the World'
    'Keywords': 'Alan Turing, Artificial Intelligence, Enigma'


# NIMAGES
# Definimos el n煤mero de im谩genes con las que vamos a trabajar
# Normalmente ser谩n ocho.

NIMAGES: 8

# BOXCOLOR
# Definimos el color de la caja de texto

BORDERCOLOR:
  - 101
  - 67
  - 33

BOXCOLOR:
  - 245
  - 234
  - 208

# IMAGES
# Definimos el nombre de las im谩genes sobre las que vamos a procesar el texto

IMAGES:
  - "Alan_Turing_01.webp"
  - "Alan_Turing_02.webp"
  - "Alan_Turing_03.webp"
  - "Alan_Turing_04.webp"
  - "Alan_Turing_05.webp"
  - "Alan_Turing_06.webp"
  - "Alan_Turing_07.webp"
  - "Alan_Turing_08.webp"

# TEXTS
# Definimos los textos, en castellano y en ingl茅s, que ir谩n en las figuras. Son dos listas con cadenas
# de texto, tantas cadenas como im谩genes queramos procesar. Una lista contiene los textos en castellano
# y la otra lista contiene los textos en ingl茅s

TEXTS:
  SPANISH:
    - "Alan Turing, un matem谩tico y l贸gico brit谩nico, estaba destinado a cambiar el curso de la historia con su mente brillante y su capacidad para resolver problemas complejos."
    - "En 1939, la Segunda Guerra Mundial desat贸 una lucha devastadora en Europa. Las potencias aliadas necesitaban una ventaja crucial para vencer a las fuerzas del Eje."
    - "El ej茅rcito alem谩n usaba la m谩quina Enigma para transmitir mensajes cifrados. Este sistema era tan complejo que se cre铆a irrompible, poniendo a los aliados en una posici贸n de desventaja."
    - "Alan Turing fue reclutado para trabajar en Bletchley Park, el centro neur谩lgico de los esfuerzos de descifrado de los aliados. All铆 se enfrentar铆a al mayor reto de su vida: descifrar Enigma."
    - "Turing dise帽贸 la m谩quina Bombe, un dispositivo electromec谩nico que ayud贸 a automatizar el proceso de descifrado de los c贸digos de Enigma. Fue un avance crucial en la guerra criptogr谩fica."
    - "En 1941, el equipo de Turing descifr贸 con 茅xito los primeros mensajes Enigma, marcando un punto de inflexi贸n en la guerra. A partir de este momento, los aliados tuvieron acceso a informaci贸n crucial del enemigo."
    - "El trabajo de Turing y su equipo permiti贸 a los aliados anticipar y frustrar los movimientos de las fuerzas del Eje, salvando miles de vidas y acortando la duraci贸n de la guerra."
    - "A pesar de su tr谩gico final, el trabajo de Turing sent贸 las bases de la inform谩tica moderna. Su legado vive en cada computadora y en cada avance tecnol贸gico que transform贸 el mundo."

  ENGLISH:
    - "Alan Turing, a British mathematician and logician, was destined to change the course of history with his brilliant mind and ability to solve complex problems."
    - "In 1939, World War II unleashed a devastating conflict in Europe. The Allied powers needed a crucial advantage to defeat the Axis forces."
    - "The German military used the Enigma machine to transmit encrypted messages. This system was so complex it was believed to be unbreakable, putting the Allies at a disadvantage."
    - "Alan Turing was recruited to work at Bletchley Park, the nerve center of the Allies' decryption efforts. There, he would face the greatest challenge of his life: breaking Enigma."
    - "Turing designed the Bombe machine, an electromechanical device that helped automate the process of breaking Enigma codes. It was a crucial breakthrough in the cryptographic war."
    - "In 1941, Turings team successfully decoded the first Enigma messages, marking a turning point in the war. From then on, the Allies had access to crucial enemy information."
    - "Turings work and his team allowed the Allies to anticipate and thwart Axis movements, saving thousands of lives and shortening the wars duration."
    - "Despite his tragic end, Turings work laid the foundations of modern computing. His legacy lives on in every computer and technological advancement that transformed the world."

LINKEDIN:
    SPANISH: |
         Rompiendo C贸digos: Alan Turing y la Computaci贸n que Cambi贸 el Mundo 火

        Durante la Segunda Guerra Mundial, Alan Turing no solo fue un matem谩tico brillante, sino el hombre que descifr贸 los c贸digos de Enigma, un avance crucial que permiti贸 a los aliados anticipar los movimientos del enemigo y salvar miles de vidas. Pero su legado no se detiene ah铆. Turing sent贸 las bases de la inform谩tica moderna, dise帽ando la "M谩quina de Turing", un concepto que es el coraz贸n de las computadoras de hoy.

        A pesar de los desaf铆os personales y profesionales que enfrent贸, su contribuci贸n fue clave para el desarrollo del mundo digital que hoy conocemos. Su visi贸n matem谩tica, su creatividad y su capacidad para resolver problemas complejos hicieron de 茅l una de las mentes m谩s influyentes del siglo XX.

        #Peque帽asHistoriasDeTecnolog铆a #AlanTuring #Inform谩tica #HistoriaDeLaComputaci贸n #Innovaci贸n
    ENGLISH: |
         Breaking Codes: Alan Turing and the Computing that Changed the World 火

        During World War II, Alan Turing wasnt just a brilliant mathematician; he was the man who broke the Enigma codes, a crucial breakthrough that allowed the Allies to anticipate enemy moves and save thousands of lives. But his legacy doesnt stop there. Turing laid the foundations of modern computing by designing the "Turing Machine," a concept that forms the core of todays computers.

        Despite the personal and professional challenges he faced, his contribution was key to the development of the digital world we now live in. His mathematical insight, creativity, and problem-solving abilities made him one of the most influential minds of the 20th century.

        #LittleTalesOfTechnology #AlanTuring #Computing #HistoryOfComputation #Innovation
